name : Create Pull Request Title

on : pull_request
  push :
    branches :
        = '*'

jobs :
  create_pull_request_title :
    runs-on : ubuntu-latest
    steps :
      - name : Checkout code
      - uses : actions/checkout@v2

      - name : Determine the directory
      - id : determine_dir
      - run : echo "::set-output name=dir::$(basename $(pwd))"

      - name : Extract branch name
        id : extract_branch_name
        run : |
          branch_name = $(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "::set-output name=branch::$branch_name"

      - name : Use appropriate PR template
        run : |
          dir="${{ steps.determine_dir.outputs.dir }}"
          case $dir in
            gpt)
              template="gpt_PULL_REQUEST_TEMPLATE.md"
              ;;
            backend)
              template="backend_PULL_REQUEST_TEMPLATE.md"
              ;;
            frontend)
              template="frontend_PULL_REQUEST_TEMPLATE.md"
              ;;
            esac
            cp "$template" ".github/PULL_REQUEST_TEMPLATE.md"

      - name : Commit changes
        run : |
          git config user.name "Your Name"
          git add .github/PULL_REQUEST_TEMPLATE.md
          git commit -m "Update pull request template"
          git push
